### ISSUE TITLE
Is the color always set to #ededed ?

### ISSUE THREAD

**Issue by HelloRusk** [actions-ecosystem/action-add-labels#193]
## What you want to add

(This is just a question)

First of all, thank you for creating such a useful workflow.
After I tried creating new labels for my purpose, I found the color of the label fixed to `#ededed`.
Is it true that when we create a label in this workflow that we haven't prepared yet, the color will always be the same?
If so, it might be more helpful to mention that in the README.

## Why this is needed

Just for my clarification

**Comment by micnncim** [comment]
If we create new labels via GitHub API without specifying a color, the color is always `#ededed`.

**Comment by HelloRusk** [comment]
thanks for your comment
